spring:
  application:
    name: query-service
  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.example.common.event
        spring.json.value.default.type: com.example.common.event.OrderEvent
server:
  port: 8082